doctrine:
    dbal:
            dbname: micke.niepceron
            host: 10.5.10.1
            port: 3306
            user: micke.niepceron
            password: EKGdbeMx
            driver: pdo_mysql
            # if the url option is specified, it will override the above config
            url: mysql://micke.niepceron:EKGdbeMx@10.5.10.1:3306/micke.niepceron

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
